site_name: The BackBee documentation
site_url: http://www.backbee.com/
site_description: The BackBee documentation

repo_url: https://github.com/backbee/docs

docs_dir: doc
theme_dir: 'blogbee'

pages:
    - 'Introduction': 'index.md'
    - 'Developer documentation':
        - 'Requirements': 'developer-documentation/requirements.md'
        - 'Installation': 'developer-documentation/installation.md'
        - 'Architecture': 'developer-documentation/architecture.md'
        - 'Configuration': 'developer-documentation/configuration.md'
        - 'Project Architecture': 'developer-documentation/project_architecture.md'
    - 'Cookbooks':
        - 'Create bundle administration': 'developer-documentation/cookbooks/create_bundle_administration.md'
        - 'Create new commands': 'developer-documentation/cookbooks/create_new_commands.md'
        - 'Create new templating helpers': 'developer-documentation/cookbooks/create_new_templating_helpers.md'
        - 'Customize error pages': 'developer-documentation/cookbooks/customize_error_pages.md'
        - 'Ease debugging with the Web Profiler': 'developer-documentation/cookbooks/ease_debugging_with_profiler.md'
        - 'Use Swift Mailer in BackBee': 'developer-documentation/cookbooks/use_swift_mailer_in_backbee.md'
        - 'Layout creation using LayoutBuilderBundle': 'developer-documentation/cookbooks/layout_creation.md'
    - 'Components':
        - 'Bundle': 'developer-documentation/components/bundle.md'
        - 'Cache': 'developer-documentation/components/cache.md'
        - 'ClassContent': 'developer-documentation/components/classcontent.md'
        - 'Config': 'developer-documentation/components/config.md'
        - 'Event Listener': 'developer-documentation/components/event_listener.md'
        - 'Nested Node': 'developer-documentation/components/nested_node.md'
        - 'Renderer': 'developer-documentation/components/renderer.md'
        - 'Routing': 'developer-documentation/components/routing.md'
        - 'Security': 'developer-documentation/components/security.md'
        - 'Translation': 'developer-documentation/components/translation.md'

copyright: Copyright &copy; 2014-2015, <a href="http://www.backbee.com">BackBee project</a>.
google_analytics: ['UA-3459992-27', 'docs.backbee.com']
